---
# Edge Services Role - Network management and edge AI (crtr)
# Basic structure that grows with needs

- name: Edge Services Configuration
  hosts: edge_services
  become: yes
  vars:
    # Basic service configuration - extend as needed
    required_services:
      - pihole-FTL
      - caddy
      - ssh
    
    optional_services:
      - hailo-hdmi-analyzer
      - ttyd
      - atuin-server
  
  tasks:
    - name: Gather hardware facts
      setup:
        gather_subset: 
          - hardware
          - network
      tags: [always]
      
    - name: Validate hardware profile
      assert:
        that:
          - ansible_architecture == "aarch64"
          - ansible_memtotal_mb >= 8192
        msg: "Hardware doesn't match pi5_edge profile"
      tags: [validation]
    
    - name: Ensure core network services
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: "{{ required_services }}"
      tags: [network_services]
    
    - name: Check service status
      command: systemctl is-active "{{ item }}"
      loop: "{{ required_services }}"
      register: service_status
      failed_when: false
      changed_when: false
      tags: [health_check]
    
    - name: Report service health
      debug:
        msg: "{{ item.item }}: {{ item.stdout }}"
      loop: "{{ service_status.results }}"
      tags: [health_check]
    
    # Placeholder for edge AI services - expand when ready
    - name: Edge AI service management
      block:
        - name: Check Hailo hardware
          stat:
            path: /dev/hailo0
          register: hailo_device
          
        - name: Hailo service status
          systemd:
            name: hailo-hdmi-analyzer
            state: started
            enabled: yes
          when: hailo_device.stat.exists
          ignore_errors: yes
          
      tags: [edge_ai]
      
    # Storage management
    - name: Ensure NAS mount points
      file:
        path: /cluster-nas
        state: directory
        mode: '0755'
      tags: [storage]
      
    - name: Validate storage availability
      stat:
        path: /cluster-nas
      register: storage_check
      tags: [storage]
      
    - name: Storage health check
      debug:
        msg: "Cluster storage: {{ 'Available' if storage_check.stat.exists else 'Missing' }}"
      tags: [health_check]