---
# Mobile Access Role - Lightweight monitoring and remote access (snitcher)
# Minimal footprint for monitoring and mobile connectivity

- name: Mobile Access Configuration
  hosts: mobile_access
  become: yes
  vars:
    # Lightweight services for mobile access
    access_services:
      - ssh
      - monitoring-agent
    
    # Minimal resource configuration
    resource_profile: minimal
    
  tasks:
    - name: Gather basic system facts
      setup:
        gather_subset:
          - hardware
          - network
      tags: [always]
      
    - name: Validate mobile hardware profile
      block:
        - name: Check basic requirements
          debug:
            msg: |
              Architecture: {{ ansible_architecture }}
              Memory: {{ ansible_memtotal_mb }}MB
              Network: {{ ansible_default_ipv4.address }}
              
      tags: [validation]
    
    # SSH access optimization
    - name: Configure SSH for mobile access
      block:
        - name: Ensure SSH service
          systemd:
            name: ssh
            state: started
            enabled: yes
            
        - name: Verify SSH configuration
          command: sshd -t
          register: ssh_config_test
          failed_when: ssh_config_test.rc != 0
          changed_when: false
          
      tags: [ssh_access]
    
    # Lightweight monitoring agent
    - name: Setup monitoring client
      block:
        - name: Create monitoring directory
          file:
            path: /var/lib/monitoring
            state: directory
            mode: '0755'
            
        - name: Basic system monitoring script
          copy:
            content: |
              #!/bin/bash
              # Basic monitoring for mobile node
              echo "Timestamp: $(date)"
              echo "Uptime: $(uptime)"
              echo "Memory: $(free -h | awk '/^Mem:/ {print $3 "/" $2}')"
              echo "Disk: $(df -h / | tail -1 | awk '{print $3 "/" $2 " (" $5 ")"}')"
              echo "Network: $(ip route get 1.1.1.1 | grep -oP 'src \K\S+' || echo 'disconnected')"
            dest: /var/lib/monitoring/system-status.sh
            mode: '0755'
            
      tags: [monitoring]
    
    # Cluster connectivity check
    - name: Test cluster connectivity
      block:
        - name: Ping cluster nodes
          command: ping -c 1 {{ item }}
          loop:
            - 192.168.254.10  # cooperator
            - 192.168.254.20  # projector
            - 192.168.254.30  # director
          register: cluster_ping
          failed_when: false
          changed_when: false
          
        - name: Report cluster connectivity
          debug:
            msg: "{{ item.item }}: {{ 'Reachable' if item.rc == 0 else 'Unreachable' }}"
          loop: "{{ cluster_ping.results }}"
          
      tags: [connectivity]
    
    # Basic cluster storage access
    - name: Setup cluster storage access
      block:
        - name: Create mount point
          file:
            path: /cluster-nas
            state: directory
            mode: '0755'
            
        - name: Test NFS connectivity
          command: showmount -e 192.168.254.10
          register: nfs_test
          failed_when: false
          changed_when: false
          
        - name: Mount cluster storage if available
          mount:
            path: /cluster-nas
            src: "192.168.254.10:/cluster-nas"
            fstype: nfs4
            opts: "ro,soft,timeo=10"
            state: mounted
          when: nfs_test.rc == 0
          ignore_errors: yes
          
      tags: [storage]
    
    # Mobile-optimized services
    - name: Configure for mobile use
      block:
        - name: Setup low-power monitoring
          cron:
            name: "cluster health check"
            minute: "*/15"
            job: "/var/lib/monitoring/system-status.sh >> /var/log/mobile-monitoring.log 2>&1"
            
        - name: Log rotation for mobile
          logrotate:
            name: mobile-monitoring
            path: /var/log/mobile-monitoring.log
            options:
              - daily
              - missingok
              - rotate 7
              - compress
              - notifempty
              
      tags: [mobile_optimization]
    
    # Health reporting
    - name: Mobile node health check
      block:
        - name: System resource summary
          shell: |
            echo "Mobile node status:"
            echo "- Hostname: $(hostname)"
            echo "- Load: $(uptime | awk '{print $NF}')"
            echo "- Memory: $(free | awk '/^Mem:/ {printf "%.0f%%\n", $3*100/$2}')"
            echo "- Storage: $(df -h / | tail -1 | awk '{print $5}')"
            echo "- SSH: $(systemctl is-active ssh)"
          register: mobile_status
          changed_when: false
          
        - name: Report mobile node readiness
          debug:
            msg: "{{ mobile_status.stdout_lines }}"
            
      tags: [health_check]
    
    # Placeholder for additional mobile services
    - name: Mobile access ready
      debug:
        msg: "Mobile access node configured for lightweight cluster monitoring and remote access"
      tags: [mobile_ready]