version: '3.8'

# Colab Cluster Services
# Deploy with: docker compose up -d [SERVICE_NAME]

services:
  # Semaphore - Ansible UI
  semaphore:
    image: semaphoreui/semaphore:latest
    container_name: semaphore
    environment:
      SEMAPHORE_DB_DIALECT: bolt
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ADMIN_PASSWORD: ${SEMAPHORE_ADMIN_PASSWORD:-changeme}
      SEMAPHORE_ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@local}
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: ${SEMAPHORE_ACCESS_KEY:-changeme}
    volumes:
      - semaphore_data:/home/semaphore
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - colab

  # Prometheus - Metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=${PROMETHEUS_RETENTION:-15d}'
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - colab

  # Grafana - Metrics visualization
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-changeme}
      GF_SERVER_ROOT_URL: ${GRAFANA_URL:-http://localhost:3001}
      GF_SERVER_HTTP_PORT: 3001
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    ports:
      - "3001:3001"
    restart: unless-stopped
    networks:
      - colab

volumes:
  semaphore_data:
  prometheus_data:
  grafana_data:

networks:
  colab:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
