---
- name: Cluster Health Check
  hosts: all
  gather_facts: yes
  tasks:
    - name: Check system uptime
      command: uptime
      register: uptime_result
      changed_when: false

    - name: Check disk usage
      shell: df -h / | awk 'NR==2 {print $5}'
      register: disk_usage
      changed_when: false

    - name: Check memory usage
      shell: free -m | awk 'NR==2 {print int($3/$2*100)}'
      register: memory_usage
      changed_when: false

    - name: Check if NFS mounted
      stat:
        path: /cluster-nas
      register: nfs_mount

    - name: Display health summary
      debug:
        msg: |
          Node: {{ inventory_hostname }}
          IP: {{ ansible_default_ipv4.address }}
          Uptime: {{ uptime_result.stdout }}
          Disk Usage: {{ disk_usage.stdout }}
          Memory Usage: {{ memory_usage.stdout }}%
          NFS Mounted: {{ nfs_mount.stat.exists }}
