---
- name: Restart Cluster Services
  hosts: all
  become: yes
  vars:
    services:
      crtr:
        - caddy
        - semaphore
        - pihole-FTL
      prtr:
        - ssh
      snitcher:
        - ssh
  tasks:
    - name: Restart service
      systemd:
        name: "{{ service_name }}"
        state: restarted
        daemon_reload: yes
      when: service_name is defined

    - name: Restart all services for host
      systemd:
        name: "{{ item }}"
        state: restarted
      loop: "{{ services[inventory_hostname] | default([]) }}"
      when: service_name is not defined
