---
- name: Check Critical Services Status
  hosts: all
  gather_facts: no
  tasks:
    - name: Define services to check per host
      set_fact:
        services_to_check:
          cooperator:
            - caddy
            - pihole-FTL
            - semaphore
            - nfs-kernel-server
            - ssh
          projector:
            - ssh

    - name: Check service status
      systemd:
        name: "{{ item }}"
      register: service_status
      loop: "{{ services_to_check[inventory_hostname] | default(['ssh']) }}"
      ignore_errors: yes

    - name: Report service status
      debug:
        msg: |
          Node: {{ inventory_hostname }}
          Service Status:
          {% for result in service_status.results %}
          - {{ result.item }}: {{ result.status.ActiveState | default('unknown') }}
          {% endfor %}
