---
- name: Configure NFS mounts for /cluster-nas across all nodes
  hosts: all
  become: yes
  vars:
    nfs_server: "192.168.254.10"
    nfs_path: "/cluster-nas"
    mount_point: "/cluster-nas"
    
  tasks:
    - name: Install NFS client utilities
      package:
        name: nfs-common
        state: present
      when: ansible_hostname != "cooperator"
      
    - name: Create mount point directory
      file:
        path: "{{ mount_point }}"
        state: directory
        mode: '0755'
      when: ansible_hostname != "cooperator"
      
    - name: Mount NFS share temporarily to test
      mount:
        src: "{{ nfs_server }}:{{ nfs_path }}"
        path: "{{ mount_point }}"
        fstype: nfs
        opts: "rw,sync,hard,intr"
        state: mounted
      when: ansible_hostname != "cooperator"
      
    - name: Add NFS mount to /etc/fstab for persistence
      mount:
        src: "{{ nfs_server }}:{{ nfs_path }}"
        path: "{{ mount_point }}"
        fstype: nfs
        opts: "rw,sync,hard,intr,_netdev"
        state: present
      when: ansible_hostname != "cooperator"
      
    - name: Verify mount is working
      command: "df -h {{ mount_point }}"
      register: mount_check
      changed_when: false
      
    - name: Display mount status
      debug:
        msg: "Mount status for {{ ansible_hostname }}: {{ mount_check.stdout }}"
        
    - name: Test write permissions
      file:
        path: "{{ mount_point }}/.nfs_test_{{ ansible_hostname }}"
        state: touch
        mode: '0644'
      when: ansible_hostname != "cooperator"
      
    - name: Clean up test file
      file:
        path: "{{ mount_point }}/.nfs_test_{{ ansible_hostname }}"
        state: absent
      when: ansible_hostname != "cooperator"