---
- name: Shared Storage and NFS Audit
  hosts: all
  gather_facts: no
  vars:
    audit_output_dir: "/tmp/storage_audit_{{ ansible_date_time.epoch }}"
    shared_paths:
      - "/cluster-nas"
      - "/cluster-nas/configs"
      - "/cluster-nas/claude-code"
      - "/cluster-nas/configs/ansible"

  tasks:
    - name: Create storage audit output directory
      file:
        path: "{{ audit_output_dir }}"
        state: directory
        mode: '0755'
      delegate_to: localhost
      run_once: true

    - name: Check shared storage paths accessibility
      stat:
        path: "{{ item }}"
      register: shared_path_checks
      loop: "{{ shared_paths }}"

    - name: Check NFS mount status
      command: mount | grep cluster-nas
      register: nfs_mount_status
      failed_when: false
      changed_when: false

    - name: Check Claude Code symlink status
      stat:
        path: "~/.claude"
      register: claude_symlink_check

    - name: Get Claude symlink target if exists
      command: readlink ~/.claude
      register: claude_symlink_target
      when: claude_symlink_check.stat.islnk is defined and claude_symlink_check.stat.islnk
      failed_when: false
      changed_when: false

    - name: Check write permissions to shared areas
      shell: |
        writeable_paths=""
        for path in /cluster-nas /cluster-nas/claude-code; do
          if [ -w "$path" ]; then
            writeable_paths="$writeable_paths $path"
          fi
        done
        echo "$writeable_paths"
      register: write_permissions_check
      changed_when: false

    - name: Check disk space on shared storage
      shell: df -h /cluster-nas | tail -1
      register: disk_space_check
      when: shared_path_checks.results[0].stat.exists
      changed_when: false

    - name: Test actual file creation in writable areas
      tempfile:
        path: /cluster-nas/claude-code
        suffix: "_ansible_test"
      register: test_file_creation
      when: "/cluster-nas/claude-code" in write_permissions_check.stdout
      failed_when: false

    - name: Clean up test file
      file:
        path: "{{ test_file_creation.path }}"
        state: absent
      when: test_file_creation.path is defined
      failed_when: false

    - name: Generate shared storage report
      copy:
        content: |
          {
            "node": "{{ inventory_hostname }}",
            "timestamp": "{{ ansible_date_time.iso8601 }}",
            "shared_paths": {
          {% for result in shared_path_checks.results %}
              "{{ result.item }}": {
                "exists": {{ result.stat.exists | lower }},
                "is_directory": {{ result.stat.isdir | default(false) | lower }},
                "readable": {{ result.stat.readable | default(false) | lower }},
                "writeable": {{ result.stat.writeable | default(false) | lower }}
              }{{ ',' if not loop.last else '' }}
          {% endfor %}
            },
            "nfs_status": {
              "mounted": {{ nfs_mount_status.rc == 0 | lower }},
              "mount_info": "{{ nfs_mount_status.stdout | default('not_mounted') }}"
            },
            "claude_integration": {
              "symlink_exists": {{ claude_symlink_check.stat.exists | default(false) | lower }},
              "is_symlink": {{ claude_symlink_check.stat.islnk | default(false) | lower }},
              "symlink_target": "{{ claude_symlink_target.stdout | default('not_applicable') }}",
              "points_to_shared_config": {{ (claude_symlink_target.stdout | default('')) == '/cluster-nas/claude-code/.claude-merged' | lower }}
            },
            "permissions": {
              "writeable_paths": "{{ write_permissions_check.stdout.split() | list }}",
              "can_create_files": {{ test_file_creation.path is defined | lower }}
            },
            "disk_usage": {
              "cluster_nas_space": "{{ disk_space_check.stdout | default('unavailable') }}"
            },
            "compliance": {
              "nas_fully_accessible": {{ (shared_path_checks.results | selectattr('stat.exists', 'equalto', true) | list | length) == (shared_paths | length) | lower }},
              "nfs_properly_mounted": {{ nfs_mount_status.rc == 0 | lower }},
              "claude_properly_linked": {{ (claude_symlink_check.stat.islnk | default(false) and (claude_symlink_target.stdout | default('')) == '/cluster-nas/claude-code/.claude-merged') | lower }},
              "write_access_available": {{ "/cluster-nas/claude-code" in write_permissions_check.stdout | lower }},
              "storage_fully_functional": {{ (nfs_mount_status.rc == 0 and (shared_path_checks.results | selectattr('stat.exists', 'equalto', true) | list | length) == (shared_paths | length)) | lower }}
            }
          }
        dest: "{{ audit_output_dir }}/{{ inventory_hostname }}_storage_audit.json"
      delegate_to: localhost

    - name: Display storage audit summary
      debug:
        msg: |
          Storage audit for {{ inventory_hostname }}:
          - NFS mounted: {{ nfs_mount_status.rc == 0 }}
          - Shared paths accessible: {{ (shared_path_checks.results | selectattr('stat.exists', 'equalto', true) | list | length) }}/{{ shared_paths | length }}
          - Claude symlink correct: {{ (claude_symlink_check.stat.islnk | default(false) and (claude_symlink_target.stdout | default('')) == '/cluster-nas/claude-code/.claude-merged') }}
          - Write access: {{ "/cluster-nas/claude-code" in write_permissions_check.stdout }}
          Results: {{ audit_output_dir }}/{{ inventory_hostname }}_storage_audit.json