---
- name: Update All Cluster Systems
  hosts: all
  become: yes
  serial: 1
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      register: upgrade_result

    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Display upgrade results
      debug:
        msg: |
          Node: {{ inventory_hostname }}
          Packages upgraded: {{ upgrade_result.changed }}
          Reboot required: {{ reboot_required.stat.exists }}

    - name: Reboot if required
      reboot:
        msg: "Rebooting after system updates"
        reboot_timeout: 300
      when: reboot_required.stat.exists and ansible_hostname != 'crtr'
