---
# ZSH Alignment Test Playbook - The Ultimate Simple Test
# Tests actual user experience across all cluster nodes

- name: ZSH Alignment Test - What Users Actually Experience
  hosts: all
  gather_facts: true
  vars:
    test_script: "/cluster-nas/scripts/zsh-alignment-test.sh"
    results_dir: "/cluster-nas/logs/zsh-test-results"
    
  tasks:
    - name: Create results directory
      file:
        path: "{{ results_dir }}"
        state: directory
        mode: '0755'
      delegate_to: localhost
      run_once: true

    - name: Make test script executable
      file:
        path: "{{ test_script }}"
        mode: '0755'
        
    - name: Run ZSH alignment test
      shell: "{{ test_script }}"
      register: test_output
      failed_when: false  # Don't fail playbook if test fails
      changed_when: false
      
    - name: Display test results
      debug:
        msg: |
          ========================================
          ZSH Test Results for {{ inventory_hostname }}
          ========================================
          {{ test_output.stdout }}
          ========================================
          Exit Code: {{ test_output.rc }}
          ========================================

    - name: Copy detailed results to shared location
      copy:
        src: "/tmp/zsh_test_results_{{ inventory_hostname }}.txt"
        dest: "{{ results_dir }}/{{ inventory_hostname }}_results.txt"
        remote_src: true
      when: test_output.rc is defined

    - name: Set test status fact
      set_fact:
        zsh_test_passed: "{{ test_output.rc == 0 }}"
        zsh_test_score: "{{ test_output.stdout | regex_search('Passed: (\\d+)', '\\1') | first | default('0') }}"
        zsh_test_failures: "{{ test_output.stdout | regex_search('Failed: (\\d+)', '\\1') | first | default('0') }}"

- name: Generate cluster-wide alignment report
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create alignment summary
      template:
        src: zsh_alignment_summary.j2
        dest: "{{ results_dir }}/cluster_alignment_summary.md"
      vars:
        test_results: "{{ hostvars }}"
        test_date: "{{ ansible_date_time.date }}"
        test_time: "{{ ansible_date_time.time }}"

    - name: Display cluster summary
      debug:
        msg: |
          ========================================
          CLUSTER ZSH ALIGNMENT SUMMARY
          ========================================
          {% for host in groups['all'] %}
          {{ host }}: {{ 'PASS' if hostvars[host]['zsh_test_passed'] else 'FAIL' }} ({{ hostvars[host]['zsh_test_score'] }}/10 tests passed)
          {% endfor %}
          ========================================
          Results saved to: {{ results_dir }}/
          ========================================