---
# Ansible Playbook: Install Modern CLI Tools
# Ensures all modern CLI tools are installed consistently across all nodes

- name: Install Modern CLI Tools on All Cluster Nodes
  hosts: all
  become: yes
  vars:
    tools_dir: "{{ ansible_env.HOME }}/.local/bin"

  tasks:
    # ====================================================================
    # APT PACKAGES (Available in Debian/Ubuntu repos)
    # ====================================================================

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install modern CLI tools via apt
      apt:
        name:
          - eza # Modern ls replacement
          - bat # cat with syntax highlighting (may be batcat)
          - fd-find # Modern find replacement (may be fdfind)
          - ripgrep # Fast grep replacement
          - fzf # Fuzzy finder
          - nnn # File manager
          - git-delta # Beautiful git diffs
          - zsh # Modern shell
        state: present

    # ====================================================================
    # RUST-BASED TOOLS (Install via cargo or direct download)
    # ====================================================================

    - name: Ensure ~/.local/bin exists
      file:
        path: "{{ tools_dir }}"
        state: directory
        mode: "0755"

    - name: Check if zoxide is installed
      command: which zoxide
      register: zoxide_check
      failed_when: false
      changed_when: false

    - name: Install zoxide (smart cd)
      shell: |
        curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh
      when: zoxide_check.rc != 0

    - name: Check if dust is installed
      command: which dust
      register: dust_check
      failed_when: false
      changed_when: false

    - name: Download and install dust (visual du)
      block:
        - name: Download dust for x86_64
          get_url:
            url: "https://github.com/bootandy/dust/releases/download/v1.1.1/dust-v1.1.1-x86_64-unknown-linux-musl.tar.gz"
            dest: "/tmp/dust.tar.gz"
          when: ansible_architecture == "x86_64"

        - name: Download dust for arm64
          get_url:
            url: "https://github.com/bootandy/dust/releases/download/v1.1.1/dust-v1.1.1-aarch64-unknown-linux-musl.tar.gz"
            dest: "/tmp/dust.tar.gz"
          when: ansible_architecture == "aarch64"

        - name: Extract and install dust
          shell: |
            cd /tmp
            tar -xzf dust.tar.gz
            cp dust-*/dust {{ tools_dir }}/
            chmod +x {{ tools_dir }}/dust
            rm -rf dust-* dust.tar.gz
      when: dust_check.rc != 0

    - name: Check if starship is installed
      command: which starship
      register: starship_check
      failed_when: false
      changed_when: false

    - name: Install starship (beautiful prompt)
      shell: |
        curl -sS https://starship.rs/install.sh | sh -s -- -b {{ tools_dir }} --yes
      when: starship_check.rc != 0

    - name: Check if atuin is installed
      command: which atuin
      register: atuin_check
      failed_when: false
      changed_when: false

    - name: Install atuin (smart history)
      shell: |
        curl --proto '=https' --tlsv1.2 -LsSf https://setup.atuin.sh | sh -s -- --no-modify-path
        # Move from default location to ~/.local/bin for consistency
        if [ -f ~/.atuin/bin/atuin ]; then
          cp ~/.atuin/bin/atuin {{ tools_dir }}/
        fi
      when: atuin_check.rc != 0

    # ====================================================================
    # VERIFICATION
    # ====================================================================

    - name: Verify all tools are accessible
      command: "{{ item }}"
      register: tool_verification
      failed_when: false
      changed_when: false
      loop:
        - "eza --version"
        - "bat --version || batcat --version"
        - "fd --version || fdfind --version"
        - "rg --version"
        - "fzf --version"
        - "nnn -V"
        - "delta --version"
        - "zoxide --version"
        - "dust --version"
        - "starship --version"
        - "atuin --version"

    - name: Display verification results
      debug:
        msg: "Tool verification: {{ item.cmd }} - {{ 'OK' if item.rc == 0 else 'FAILED' }}"
      loop: "{{ tool_verification.results }}"

    # ====================================================================
    # SYSTEM INTEGRATION (NO USER CONFIGS)
    # ====================================================================

    - name: Create tools availability script for system use
      copy:
        dest: /usr/local/bin/cluster-tools-check
        content: |
          #!/bin/bash
          # Co-lab Cluster Tools Availability Check
          # System-level tool validation script

          echo "=== Modern CLI Tools Status ==="
          for tool in eza bat batcat fd fdfind rg fzf nnn delta zoxide dust starship atuin; do
              if command -v "$tool" >/dev/null 2>&1; then
                  version=$($tool --version 2>/dev/null | head -1 || echo "installed")
                  echo "✓ $tool: $version"
              else
                  echo "✗ $tool: not found"
              fi
          done

          echo
          echo "=== Tool Detection Variables ==="
          echo "# Copy these to your shell profile for tool detection:"
          echo "export HAS_EZA=\$(command -v eza >/dev/null 2>&1 && echo 1 || echo 0)"
          echo "export HAS_BAT=\$(command -v bat >/dev/null 2>&1 || command -v batcat >/dev/null 2>&1 && echo 1 || echo 0)"
          echo "export HAS_FD=\$(command -v fd >/dev/null 2>&1 || command -v fdfind >/dev/null 2>&1 && echo 1 || echo 0)"
          echo "export HAS_RG=\$(command -v rg >/dev/null 2>&1 && echo 1 || echo 0)"
          echo "export HAS_FZF=\$(command -v fzf >/dev/null 2>&1 && echo 1 || echo 0)"
          echo "export HAS_ZOXIDE=\$(command -v zoxide >/dev/null 2>&1 && echo 1 || echo 0)"
          echo "export HAS_STARSHIP=\$(command -v starship >/dev/null 2>&1 && echo 1 || echo 0)"
        mode: "0755"

    - name: Add tools to system profile (minimal detection only)
      blockinfile:
        path: /etc/profile.d/01-modern-tools.sh
        create: yes
        mode: "0644"
        block: |
          # Modern CLI Tools System Integration
          # Tool availability for system users - NO USER CONFIGURATIONS

          # Add user-local tool paths to system PATH
          if [ -d "$HOME/.local/bin" ]; then
              export PATH="$HOME/.local/bin:$PATH"
          fi

          # System-wide tool availability check function
          check_modern_tools() {
              /usr/local/bin/cluster-tools-check
          }
        marker: "# {mark} MODERN TOOLS SYSTEM INTEGRATION"
