#!/bin/bash
# This script SSHs to each node, runs commands to get ACTUAL system info,
# and writes it to a markdown file. It's not "updating documentation" magically -
# it's just gathering real data and formatting it.

DOC_FILE="/cluster-nas/CURRENT_STATE_AUTO.md"

echo "# Cluster State - Auto-Generated $(date +%Y-%m-%d)" > $DOC_FILE
echo "This is NOT documentation - it's actual system state" >> $DOC_FILE
echo "" >> $DOC_FILE

# Check each node and get REAL info
for node in "prtr@192.168.254.20" "drtr@192.168.254.30" "snitcher@192.168.254.96"; do
  hostname=$(echo $node | cut -d@ -f1)
  echo "## $hostname" >> $DOC_FILE
  
  # Try to SSH and get actual system info
  if ssh -o ConnectTimeout=2 $node 'echo "alive"' &>/dev/null; then
    echo "- Status: ONLINE" >> $DOC_FILE
    ssh $node 'echo "- RAM: $(free -h | grep Mem | awk "{print \$2}")"' >> $DOC_FILE 2>/dev/null
    ssh $node 'docker --version &>/dev/null && echo "- Docker: YES" || echo "- Docker: NO"' >> $DOC_FILE
    ssh $node 'docker ps --format "- Container: {{.Names}} ({{.Status}})" 2>/dev/null | head -5' >> $DOC_FILE
  else
    echo "- Status: OFFLINE or UNREACHABLE" >> $DOC_FILE
  fi
  echo "" >> $DOC_FILE
done

echo "Generated by: $0" >> $DOC_FILE