---
# VARIABLE PRECEDENCE DEMONSTRATION
# Run: ansible-playbook variable_precedence_demo.yml -i inventory/hosts.yml

- name: Demonstrate Variable Precedence
  hosts: cooperator
  vars:
    # LEVEL 6: Playbook vars (high priority)
    demo_message: "Set in playbook"
    
  tasks:
    - name: Show all the places ansible_user could come from
      debug:
        msg: |
          Current ansible_user: {{ ansible_user }}
          
          Variable precedence hierarchy:
          1. role defaults: (lowest - would be in roles/*/defaults/main.yml)
          2. inventory file: {{ hostvars[inventory_hostname]['ansible_user'] }} (from hosts.yml)
          3. group_vars/all: (would be in group_vars/all/main.yml) 
          4. group_vars/edge_services: (would be in group_vars/edge_services/main.yml)
          5. host_vars/cooperator: (would be in host_vars/cooperator/main.yml)
          6. playbook vars: demo_message = "{{ demo_message }}"
          7. extra vars: (highest - from command line with -e)
          
          Hardware profile (from group_vars/all): {{ hardware_profiles[hardware_profile] }}
          Node role (from inventory): {{ node_role }}
          
    - name: Show how to override at different levels
      debug:
        msg: "Run with: -e 'ansible_user=override' to see command line override"